### ISSUE TITLE
Bootstrap not creating validated_software

### ISSUE THREAD

**Issue by nopg** [nautobot/nautobot-app-ssot#830]
### Environment
* Python version:  3.11.4 & 3.12
* Nautobot version:  2.4.8
* nautobot-ssot version: 3.8.1

When adding `validated_software` to the `global_settings.yml` file, and running the Bootstrap -> Nautobot Job, I expect to see new `validated_software` in the CREATES diff, and created in Nautobot.

Logs show the `validated_software` get added to the diffsync store, but there is no DIFF (create/update/delete) for validated_software objects, so nothing gets added.d

### Steps to Reproduce
1. Nautobot with a`Software` version already existing in Nautobot
2. Add new `validated_software` into global_settings.py (for example, below)
```
validated_software:
  device_roles:
    - MY_SWITCHES
  device_types: []
  devices: []
  inventory_items: []
  object_tags: []
  preferred_version: true
  software: cisco.ios.ios - 16.8.2
  tags: []
  valid_since: '2018-04-01'
  valid_until: '2021-12-30'
```
3. Run the Bootstrap -> Nautobot SSOT job
4. Observe results (logs about the validated_software, but nothing created)
